diff casos_de_teste/c1.original.txt.cmp casos.old/c1.original.txt.cmp
read -p "..."
diff casos_de_teste/c2.original.txt.cmp casos.old/c2.original.txt.cmp
read -p "..."
diff casos_de_teste/c3.original.txt.cmp casos.old/c3.original.txt.cmp
read -p "..."
diff casos_de_teste/c4.original.txt.cmp casos.old/c4.original.txt.cmp
read -p "..."
diff casos_de_teste/c5.original.txt.cmp casos.old/c5.original.txt.cmp
read -p "..."
diff casos_de_teste/c6.original.txt.cmp casos.old/c6.original.txt.cmp
read -p "..."
diff casos_de_teste/c7.original.txt.cmp casos.old/c7.original.txt.cmp
read -p "..."
diff casos_de_teste/c8.original.txt.cmp casos.old/c8.original.txt.cmp
read -p "..."
diff casos_de_teste/c9.original.txt.cmp casos.old/c9.original.txt.cmp
read -p "..."